Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
    v.name = "othf-ws-#{rand(01..99)}"
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.define "workstation" do |workstation|
    workstation.vm.hostname = "othf-ws-#{rand(01..99)}"
	workstation.vm.guest = :windows
    workstation.vm.boot_timeout = 600
    workstation.vm.graceful_halt_timeout = 600
	workstation.winrm.retry_limit = 30
    workstation.winrm.retry_delay = 10
	workstation.vm.network "private_network", type: "dhcp"
	workstation.vm.box = "gusztavvargadr/windows-10"
	workstation.vm.provision "file", source: "inputs.conf", destination: "c:\\users\\vagrant\\desktop\\inputs.conf"
	workstation.vm.provision "file", source: "outputs.conf", destination: "c:\\users\\vagrant\\desktop\\outputs.conf"
	workstation.vm.provision "file", source: "ConfigAuditing.ps1", destination: "c:\\users\\vagrant\\desktop\\ConfigAuditing.ps1"
	workstation.vm.provision "provision-script", type: "shell", path: "provision.ps1"
	end

  end