Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
    v.name = "othf-server-#{rand(01..99)}"
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.define "server" do |server|
    server.vm.hostname = "othf-srv-#{rand(01..99)}"
	server.vm.guest = :windows
    server.vm.boot_timeout = 600
    server.vm.graceful_halt_timeout = 600
	server.winrm.retry_limit = 30
    server.winrm.retry_delay = 10
	server.vm.network "private_network", type: "dhcp"
	server.vm.box = "gusztavvargadr/windows-server"
	server.vm.provision "file", source: "ConfigAuditing.ps1", destination: "c:\\users\\vagrant\\desktop\\ConfigAuditing.ps1"
	server.vm.provision "provision-script", type: "shell", path: "provision.ps1"
	end

  config.vm.provision :windows_domain do |domain|
	domain.domain = "othf.local"
	domain.username = "administrator"
	domain.password = "!P@ssword123456"
	domain.primary_dns = "10.10.1.1"
	end
  end