Vagrant.configure("2") do |config|
  
  config.vm.provider "virtualbox" do |v|
    v.name = "DC1"
    v.memory = 2048
    v.cpus = 1
  end

  config.vm.define "dc" do |dc|
    dc.vm.hostname = "dc1"
	dc.vm.guest = :windows
    dc.vm.boot_timeout = 600
    dc.vm.graceful_halt_timeout = 600
	dc.winrm.retry_limit = 30
    dc.winrm.retry_delay = 10
	dc.vm.network "private_network", ip: "192.168.1.2"
	dc.vm.box = "StefanScherer/windows_2016"
	dc.vm.provision "file", source: "InstallDomain_1.ps1", destination: "c:\\users\\vagrant\\desktop\\InstallDomain_1.ps1"
	dc.vm.provision "file", source: "InstallDHCP_2.ps1", destination: "c:\\users\\vagrant\\desktop\\InstallDHCP_2.ps1"
	dc.vm.provision "file", source: "inputs.conf", destination: "c:\\users\\vagrant\\desktop\\inputs.conf"
	dc.vm.provision "file", source: "outputs.conf", destination: "c:\\users\\vagrant\\desktop\\outputs.conf"
	dc.vm.provision "file", source: "ConfigAuditing.ps1", destination: "c:\\users\\vagrant\\desktop\\ConfigAuditing.ps1"
	dc.vm.provision "provision-script", type: "shell", path: "provision.ps1"
	end
  end