Vagrant.configure("2") do |config|
  config.vm.box = "jmeacham/splunk"
  config.vm.box_version = "0.0.1"
  config.vm.network "private_network", ip: "10.10.1.3", netmask: "24"
  config.vm.provision "shell", inline: "sudo ufw disable"
  config.vm.provision "shell", path: "setup2.sh"
end